import { FoodItem, Medication, RecipeItem } from '../types';
import { addDaysToDate, getTodayDateString } from './foodDatabase';

const today = getTodayDateString();

export const INITIAL_FOOD_ITEMS: FoodItem[] = [
  {
    id: 'f-1',
    name: 'Baby Spinach',
    category: 'produce',
    location: 'fridge',
    purchaseDate: addDaysToDate(today, -3),
    expirationDate: addDaysToDate(today, 1), // Expiring tomorrow!
    quantity: 1,
    unit: 'pack (200g)',
    rotPreventionTip: 'Place a dry paper towel in container to absorb leaf sweat.',
    canFreeze: true,
    estimatedCost: 3.5,
  },
  {
    id: 'f-2',
    name: 'Fresh Whole Milk',
    category: 'dairy',
    location: 'fridge',
    purchaseDate: addDaysToDate(today, -5),
    expirationDate: addDaysToDate(today, 2), // Expiring in 2 days
    quantity: 1,
    unit: 'carton (1L)',
    rotPreventionTip: 'Store in central fridge body, never on door pockets where temp swings.',
    canFreeze: true,
    estimatedCost: 4.2,
  },
  {
    id: 'f-3',
    name: 'Boneless Chicken Breast',
    category: 'meat',
    location: 'fridge',
    purchaseDate: addDaysToDate(today, -1),
    expirationDate: addDaysToDate(today, 1), // Expiring tomorrow!
    quantity: 500,
    unit: 'grams',
    rotPreventionTip: 'Cook today or freeze immediately to avoid bacterial spoilage.',
    canFreeze: true,
    estimatedCost: 8.0,
  },
  {
    id: 'f-4',
    name: 'Greek Yogurt (Plain)',
    category: 'dairy',
    location: 'fridge',
    purchaseDate: addDaysToDate(today, -2),
    expirationDate: addDaysToDate(today, 5),
    quantity: 500,
    unit: 'grams',
    rotPreventionTip: 'Smooth the yogurt flat before resealing lid to minimize surface oxidation.',
    canFreeze: false,
    estimatedCost: 4.5,
  },
  {
    id: 'f-5',
    name: 'Fresh Eggs',
    category: 'dairy',
    location: 'fridge',
    purchaseDate: addDaysToDate(today, -7),
    expirationDate: addDaysToDate(today, 14),
    quantity: 10,
    unit: 'eggs',
    rotPreventionTip: 'Keep in original carton to prevent absorption of strong fridge odors.',
    canFreeze: false,
    estimatedCost: 5.0,
  },
  {
    id: 'f-6',
    name: 'Whole Grain Sliced Bread',
    category: 'bakery',
    location: 'pantry',
    purchaseDate: addDaysToDate(today, -3),
    expirationDate: addDaysToDate(today, 2),
    quantity: 8,
    unit: 'slices',
    rotPreventionTip: 'Freeze slices now! Pop directly into toaster for fresh texture without mold.',
    canFreeze: true,
    estimatedCost: 3.2,
  },
  {
    id: 'f-7',
    name: 'Roma Tomatoes',
    category: 'produce',
    location: 'pantry',
    purchaseDate: addDaysToDate(today, -2),
    expirationDate: addDaysToDate(today, 3),
    quantity: 4,
    unit: 'items',
    rotPreventionTip: 'Store stem down at room temp. If wrinkling, roast or blend into marinara sauce.',
    canFreeze: true,
    estimatedCost: 2.8,
  },
  {
    id: 'f-8',
    name: 'Rolled Oats',
    category: 'pantry',
    location: 'pantry',
    purchaseDate: addDaysToDate(today, -10),
    expirationDate: addDaysToDate(today, 90),
    quantity: 800,
    unit: 'grams',
    rotPreventionTip: 'Keep in an airtight jar in a cool, dark cabinet.',
    canFreeze: false,
    estimatedCost: 3.0,
  },
  {
    id: 'f-9',
    name: 'Ripe Bananas',
    category: 'produce',
    location: 'pantry',
    purchaseDate: addDaysToDate(today, -4),
    expirationDate: addDaysToDate(today, 1),
    quantity: 3,
    unit: 'items',
    rotPreventionTip: 'Peel and freeze in ziploc bag for quick morning smoothies.',
    canFreeze: true,
    estimatedCost: 1.8,
  },
];

export const INITIAL_MEDICATIONS: Medication[] = [
  {
    id: 'm-1',
    name: 'Metformin HCl',
    category: 'medication',
    dosage: '500 mg',
    form: 'tablet',
    frequency: 'twice_daily',
    times: ['morning', 'evening'],
    specificTimes: ['08:00', '19:30'],
    foodRule: 'with_meal',
    purpose: 'Blood sugar regulation & insulin sensitivity',
    doctorInstructions: 'Take with first bite of breakfast and dinner to prevent upset stomach and nausea.',
    pillsRemaining: 24,
    totalPills: 60,
    refillThreshold: 10,
    reminderEnabled: true,
    history: {
      [today]: {},
    },
    streakDays: 6,
  },
  {
    id: 'm-2',
    name: 'Vitamin D3 + K2',
    category: 'supplement',
    dosage: '2000 IU',
    form: 'capsule',
    frequency: 'once_daily',
    times: ['morning'],
    specificTimes: ['08:30'],
    foodRule: 'with_meal',
    purpose: 'Bone strength, immunity & mood support',
    doctorInstructions: 'Fat-soluble vitamin. Must be taken with healthy dietary fats (eggs, nuts, yogurt) for absorption.',
    pillsRemaining: 48,
    totalPills: 60,
    refillThreshold: 12,
    reminderEnabled: true,
    history: {
      [today]: {},
    },
    streakDays: 14,
  },
  {
    id: 'm-3',
    name: 'Omeprazole',
    category: 'medication',
    dosage: '20 mg',
    form: 'capsule',
    frequency: 'once_daily',
    times: ['morning'],
    specificTimes: ['07:15'],
    foodRule: 'empty_stomach',
    purpose: 'Acid reflux & stomach lining protection',
    doctorInstructions: 'Take 30-60 minutes BEFORE breakfast with a full glass of plain water.',
    pillsRemaining: 18,
    totalPills: 30,
    refillThreshold: 7,
    reminderEnabled: true,
    history: {
      [today]: {},
    },
    streakDays: 4,
  },
  {
    id: 'm-4',
    name: 'Magnesium Glycinate',
    category: 'supplement',
    dosage: '200 mg',
    form: 'tablet',
    frequency: 'once_daily',
    times: ['bedtime'],
    specificTimes: ['21:45'],
    foodRule: 'anytime',
    purpose: 'Sleep depth, muscle relaxation & nervous system rest',
    doctorInstructions: 'Take 45 minutes before sleep with a small sip of water.',
    pillsRemaining: 35,
    totalPills: 90,
    refillThreshold: 15,
    reminderEnabled: true,
    history: {
      [today]: {},
    },
    streakDays: 21,
  },
  {
    id: 'm-5',
    name: 'Omega-3 Fish Oil (EPA/DHA)',
    category: 'supplement',
    dosage: '1200 mg',
    form: 'capsule',
    frequency: 'once_daily',
    times: ['noon'],
    specificTimes: ['13:00'],
    foodRule: 'with_meal',
    purpose: 'Cardiovascular heart health & joint lubrication',
    doctorInstructions: 'Take with lunch to avoid fishy burps.',
    pillsRemaining: 52,
    totalPills: 60,
    refillThreshold: 10,
    reminderEnabled: true,
    history: {
      [today]: {},
    },
    streakDays: 18,
  },
];

export const INITIAL_RECIPES: RecipeItem[] = [
  {
    id: 'rec-1',
    title: 'Speedy Spinach, Tomato & Feta Omelette',
    description: 'A protein-packed, 10-minute skillet scramble engineered to consume your fragile spinach and tomatoes before wilting.',
    prepTime: '5 mins',
    cookTime: '6 mins',
    servings: 1,
    difficulty: 'Easy',
    caloriesPerServing: 310,
    macros: {
      protein: '22g',
      carbs: '6g',
      fat: '21g',
      fiber: '3g',
    },
    expiringItemsUsed: ['Baby Spinach', 'Roma Tomatoes', 'Fresh Eggs'],
    ingredientsRequired: [
      { name: 'Fresh Eggs', amount: '2-3 eggs', inPantry: true },
      { name: 'Baby Spinach', amount: '2 large handfuls (60g)', inPantry: true },
      { name: 'Roma Tomatoes', amount: '1 diced', inPantry: true },
      { name: 'Olive Oil or Butter', amount: '1 tsp', inPantry: true },
    ],
    pantryCoveragePercent: 100,
    instructions: [
      'Heat 1 tsp olive oil or butter in a non-stick skillet over medium-low heat.',
      'Add diced tomato and baby spinach. Sauté for 60 seconds until spinach just begins to soften.',
      'Whisk eggs in a bowl with a pinch of salt & black pepper, then pour gently over the vegetables.',
      'Tilt pan to spread evenly. Cook 2-3 minutes, fold in half, and serve hot.',
    ],
    healthBenefits: 'Loaded with lutein for vision, choline for brain focus, and iron. Ideal buffer for morning medications.',
    rotPreventionTip: 'Spinach leaves lose vitamin C rapidly once wilted; cooking it now locks in nutrients.',
    dietaryTags: ['High Protein', 'Gluten Free', 'Vegetarian', 'Quick Prep'],
  },
  {
    id: 'rec-2',
    title: 'Golden Pan-Seared Chicken with Wilted Greens',
    description: 'Juicy, seasoned chicken breast paired with sautéed spinach and warm whole-grain toast.',
    prepTime: '8 mins',
    cookTime: '12 mins',
    servings: 2,
    difficulty: 'Easy',
    caloriesPerServing: 385,
    macros: {
      protein: '42g',
      carbs: '22g',
      fat: '11g',
      fiber: '5g',
    },
    expiringItemsUsed: ['Boneless Chicken Breast', 'Baby Spinach', 'Whole Grain Sliced Bread'],
    ingredientsRequired: [
      { name: 'Boneless Chicken Breast', amount: '350g', inPantry: true },
      { name: 'Baby Spinach', amount: '120g', inPantry: true },
      { name: 'Whole Grain Sliced Bread', amount: '2 slices', inPantry: true },
      { name: 'Garlic & Olive Oil', amount: '1 tbsp', inPantry: true },
    ],
    pantryCoveragePercent: 100,
    instructions: [
      'Slice chicken breasts horizontally into even cutlets. Season with garlic, salt, paprika, and black pepper.',
      'Sear in a hot skillet with 1/2 tbsp olive oil for 4-5 minutes per side until golden (internal temp 74°C / 165°F). Remove to rest.',
      'In the same savory pan juices, toss in remaining spinach with minced garlic. Sauté for 90 seconds.',
      'Toast your whole grain bread and plate together with sliced chicken.',
    ],
    healthBenefits: 'Ultra-lean complete protein for sustained satiety and tissue repair without heavy saturated fats.',
    rotPreventionTip: 'Rescues fresh poultry right before shelf-life expires, saving $8.00 in food waste.',
    dietaryTags: ['High Protein', 'Lean Meal', 'Zero Waste Hero'],
  },
  {
    id: 'rec-3',
    title: 'High-Protein Banana Cream Overnight Oats',
    description: 'Sweet, creamy breakfast prepared in 3 minutes the night before using ripe bananas and Greek yogurt.',
    prepTime: '4 mins',
    cookTime: '0 mins (Chill)',
    servings: 1,
    difficulty: 'Easy',
    caloriesPerServing: 340,
    macros: {
      protein: '20g',
      carbs: '54g',
      fat: '6g',
      fiber: '8g',
    },
    expiringItemsUsed: ['Ripe Bananas', 'Fresh Whole Milk', 'Greek Yogurt (Plain)'],
    ingredientsRequired: [
      { name: 'Rolled Oats', amount: '1/2 cup (50g)', inPantry: true },
      { name: 'Fresh Whole Milk', amount: '1/2 cup (120ml)', inPantry: true },
      { name: 'Greek Yogurt (Plain)', amount: '1/3 cup (80g)', inPantry: true },
      { name: 'Ripe Bananas', amount: '1 mashed', inPantry: true },
    ],
    pantryCoveragePercent: 100,
    instructions: [
      'In a glass jar or small container, mash the ripe banana with a fork.',
      'Stir in rolled oats, fresh milk, and Greek yogurt until thoroughly combined.',
      'Cover with lid and refrigerate for at least 2 hours (or overnight).',
      'Enjoy chilled with an extra dash of cinnamon. No cooking required!',
    ],
    healthBenefits: 'Prebiotic beta-glucan fiber feeds healthy gut microbiota, while potassium supports healthy blood pressure.',
    rotPreventionTip: 'Overripe bananas have peak natural sweetness, eliminating any need for added refined sugar.',
    dietaryTags: ['Heart Healthy', 'No Cook', 'High Fiber', 'Vegetarian'],
  },
];
